### ISSUE TITLE
mac 下执行npm run start 报下面的错误。我的系统默认的账户是root.没有密码使用 mysql -u root -p能够成功登陆mysql

### ISSUE THREAD

**Issue by proshuai** [BetterJS/badjs-web#17]
throw err; // Rethrow non-MySQL errors
        ^
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)

**Comment by caihuiji** [comment]
请问你的NODE 版本是什么哈

**Comment by caihuiji** [comment]
https://github.com/BetterJS/badjs-web/issues/18
