### ISSUE TITLE
mysql 链接失败

### ISSUE THREAD

**Issue by gwuhaolin** [BetterJS/badjs-web#18]
mysql的root用户的默认密码是空
配置里的账号密码都是root会导致运行失败
```
"url" : "mysql://root:root@localhost:3306/badjs"
```
把默认密码改成空或者文档说明清楚

**Comment by miniflycn** [comment]
你们现在要重新搭 NodeJS ？

**Comment by caihuiji** [comment]
mysql 帐号密码一般都是root/root ，当然需要根据自己的实际环境进行配置

**Comment by proshuai** [comment]
![image](https://cloud.githubusercontent.com/assets/13295895/19712056/2f30cfee-9b6d-11e6-82d6-153fef90b6b3.png)
![image](https://cloud.githubusercontent.com/assets/13295895/19712072/48ea908c-9b6d-11e6-9ad6-2c4c0f1042cd.png)
![image](https://cloud.githubusercontent.com/assets/13295895/19712077/55d4b5f2-9b6d-11e6-84e1-4fb19e8adc0e.png)
还是有问题。没查到怎么搞，劳烦大神指导
