### ISSUE TITLE
orm 不支持node6

### ISSUE THREAD

**Issue by gwuhaolin** [BetterJS/badjs-web#19]
写死了的 orm版本 "orm": "2.1.3"
在node6上运行失败，请升级到最新的orm版本

**Comment by miniflycn** [comment]
@caihuiji 看看要不要支持Node 6，貌似Node 6稳定了

**Comment by yorts52** [comment]
6 也除了 LTS，可以支持一下

**Comment by caihuiji** [comment]
现在node 更新好快啊。 我要看看那其他模块有没有影响。

**Comment by caihuiji** [comment]
已经支持
