### ISSUE TITLE
提交信息是出现错误，主要是数据库插入时出错

### ISSUE THREAD

**Issue by lzuntalented** [BetterJS/badjs-web#22]
不清楚是环境的问题还是怎样，直接使用传递的参数插入数据库时老是出错，需要将要参数赋值给新的变量才可以使用。
会不会是target中含有不存在的表字段属性导致的

例如：service/approveService.js
add: function(target, callback) {
        var self = this;
        this.approveDao.create(target, function(err, items) {});
需要调整下面的样子
add:function(target, callback) {
        var self = this;
   
        let sqldata =   {
            userName    : target.userName,
            reply       : target.reply,
            createTime  : target.createTime,
            applyId     : target.applyId,
            applyStatus : target.applyStatus
        };
        this.approveDao.create(sqldata, function(err, items) {});

**Comment by caihuiji** [comment]
你的 node 是什么版本的。 还有 orm 模块是什么版本的。
这触发的逻辑是在审批通过的时候触发的吗？

**Comment by lzuntalented** [comment]
node版本是6.2.2，orm版本是3.1.0，这个触发是在提交信息的时候

**Comment by caihuiji** [comment]
已经修复了。 
是 orm 3.1.0 版本依赖一个 json 对象的 hasOwnProperty 方法。
而本业务是将 exrepss 的 param对象传递给orm ， 这个对象被 express 重写了， 原生 json的hasOwnProperty 没有了
