### ISSUE TITLE
查询日志体验优化项

### ISSUE THREAD

**Issue by haowuqq** [BetterJS/badjs-web#8]
1.搜索的过程中，增loading动画
2.日期与时间选择器折开，做成这样
![image](https://cloud.githubusercontent.com/assets/4533551/11865751/0fd2197e-a4e1-11e5-91de-f94c67d25396.png)
或者这样
![image](https://cloud.githubusercontent.com/assets/4533551/11865783/53c4a9f8-a4e1-11e5-9c3d-c561e56c173c.png)

**Comment by caihuiji** [comment]
loading 效果已经增加唉。  日期是控件里面就有支持的选择时间的。
